#!/usr/bin/python3
import sys

n = sys.argv[1]
x = int(n)
print(x)

if x - 2019 >= 0:
    if x - 2019 == 0:
        print("令和元年（平成31年)")
    elif x - 2019 != 0:
        ans = x - 2019
        print("令和",ans + 1,"年")
elif x - 1989 >= 0:
    if x - 1989 == 0:
        print("平成元年(昭和64年)")
    elif x - 1989 !=0:
        ans = x - 1989
        print("平成",ans + 1,"年")
elif x - 1926 >= 0:
    ans = x - 1926
    print("昭和",ans +1,"年")

